const data = {
    products: [
        {
            id: 1,
            name: 'Product 1',
            slug: 'product-1',
            price: 100,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod, nisl eget aliquam consectetur, nisl nunc aliquet nunc, euismod aliquam eros nunc euismod nunc. Donec euismod, nisl eget aliquam consectetur.',
            image: 'https://picsum.photos/id/1/200/300',
            category: 'category 1',
            brand: 'brand 1',
            rating: 4.5,
            reviews: 10,
            stock: 10,
        },
        {
            id: 2,
            name: 'Product 2',
            slug: 'product-2',
            price: 120,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod, nisl eget aliquam consectetur, nisl nunc aliquet nunc, euismod aliquam eros nunc euismod nunc. Donec euismod, nisl eget aliquam consectetur.',
            image: 'https://picsum.photos/id/4/200/300',
            category: 'category 1',
            brand: 'brand 1',
            rating: 1,
            reviews: 18,
            stock: 20,
        },
        {
            id: 3,
            name: 'Product 3',
            slug: 'product-3',
            price: 20,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod, nisl eget aliquam consectetur, nisl nunc aliquet nunc, euismod aliquam eros nunc euismod nunc. Donec euismod, nisl eget aliquam consectetur.',
            image: 'https://picsum.photos/id/5/200/300',
            category: 'category 1',
            brand: 'brand 1',
            rating: 2.5,
            reviews: 20,
            stock: 70,
        },
        {
            id: 4,
            name: 'Product 4',
            slug: 'product-4',
            price: 120,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod, nisl eget aliquam consectetur, nisl nunc aliquet nunc, euismod aliquam eros nunc euismod nunc. Donec euismod, nisl eget aliquam consectetur.',
            image: 'https://picsum.photos/id/2/200/300',
            category: 'category 1',
            brand: 'brand 1',
            rating: 5,
            reviews: 120,
            stock: 11,
        },
        {
            id: 5,
            name: 'Product 5',
            slug: 'product-5',
            price: 70,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod, nisl eget aliquam consectetur, nisl nunc aliquet nunc, euismod aliquam eros nunc euismod nunc. Donec euismod, nisl eget aliquam consectetur.',
            image: 'https://picsum.photos/id/6/200/300',
            category: 'category 1',
            brand: 'brand 1',
            rating: 4,
            reviews: 3,
            stock: 40,
        },
    ]
}

export default data;